# Generated by Django 4.1.7 on 2023-04-27 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_notes_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='user_id',
            new_name='user',
        ),
    ]
